version: "3.8"

services:
  dbe:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: gbvazco
      MYSQL_PASSWORD: EF300595
    volumes:
      - ./ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql
    networks:
      - internal

  apiecommerce:
    build:
      context: ./apie
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - dbe
    networks:
      - internal
    # Dokploy will use labels for domains, but we'll leave it as is so you can configure it.
    # labels:
    #   - "dokploy.domain=api.tudominio.com"

  webecommerce:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - dbe
    networks:
      - internal
    # labels:
    #   - "dokploy.domain=www.tudominio.com"

networks:
  internal:
    driver: bridge
